
//
//
// THIS FILE HAS BEEN GENERATED BY sameriver-generate
//
//
// DO NOT MODIFY BY HAND UNLESS YOU WANNA HAVE A GOOD TIME WHEN THE NEXT
// GENERATION DESTROYS WHAT YOU WROTE. UNLESS YOU KNOW HOW TO HAVE A GOOD TIME
//
//

package engine

func (e *Entity) GetBox() *Vec2D {
	return &e.World.em.Components.Box[e.ID]
}
func (e *Entity) GetLogic() *LogicUnit {
	return &e.World.em.Components.Logic[e.ID]
}
func (e *Entity) GetMass() *float64 {
	return &e.World.em.Components.Mass[e.ID]
}
func (e *Entity) GetMaxVelocity() *float64 {
	return &e.World.em.Components.MaxVelocity[e.ID]
}
func (e *Entity) GetMovementTarget() *Vec2D {
	return &e.World.em.Components.MovementTarget[e.ID]
}
func (e *Entity) GetPosition() *Vec2D {
	return &e.World.em.Components.Position[e.ID]
}
func (e *Entity) GetSprite() *Sprite {
	return &e.World.em.Components.Sprite[e.ID]
}
func (e *Entity) GetSteer() *Vec2D {
	return &e.World.em.Components.Steer[e.ID]
}
func (e *Entity) GetTagList() *TagList {
	return &e.World.em.Components.TagList[e.ID]
}
func (e *Entity) GetVelocity() *Vec2D {
	return &e.World.em.Components.Velocity[e.ID]
}
