
//
//
// THIS FILE HAS BEEN GENERATED BY sameriver-generate
//
//
// DO NOT MODIFY BY HAND UNLESS YOU WANNA HAVE A GOOD TIME WHEN THE NEXT
// GENERATION DESTROYS WHAT YOU WROTE. UNLESS YOU KNOW HOW TO HAVE A GOOD TIME
//
//

package engine

import (
	"github.com/veandco/go-sdl2/sdl"
)

type ComponentsTable struct {
	em             *EntityManager
	Box            [MAX_ENTITIES]sdl.Rect
	MovementTarget [MAX_ENTITIES]Vec2D
	Sprite         [MAX_ENTITIES]Sprite
	Steer          [MAX_ENTITIES]float32
	TagList        [MAX_ENTITIES]TagList
	Velocity       [MAX_ENTITIES]Vec2D
}

func (ct *ComponentsTable) Init(em *EntityManager) {
	ct.em = em
}
