//
//
// THIS FILE HAS BEEN GENERATED BY sameriver-generate
//
//
// DO NOT MODIFY BY HAND UNLESS YOU WANNA HAVE A GOOD TIME WHEN THE NEXT
// GENERATION DESTROYS WHAT YOU WROTE. UNLESS YOU KNOW HOW TO HAVE A GOOD TIME
//
//

package engine

import (
	"github.com/veandco/go-sdl2/sdl"
)

type ComponentsDataTable struct {
	em             *EntityManager
	Box            [MAX_ENTITIES]sdl.Rect
	Logic          [MAX_ENTITIES]LogicUnit
	MovementTarget [MAX_ENTITIES]Vec2D
	Position       [MAX_ENTITIES]Vec2D
	Sprite         [MAX_ENTITIES]Sprite
	Steer          [MAX_ENTITIES]float32
	TagList        [MAX_ENTITIES]TagList
	Velocity       [MAX_ENTITIES]Vec2D
}

func NewComponentsDataTable(em *EntityManager) *ComponentsDataTable {
	return &ComponentsDataTable{em: em}
}
